# Generated by Django 5.0.1 on 2024-02-06 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First name must be alphabetic.', regex='^[a-zA-Z]*$')])),
                ('last_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Last name must be alphabetic.', regex='^[a-zA-Z]*$')])),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric.', regex='^[a-zA-Z0-9]*$'), django.core.validators.MinLengthValidator(limit_value=5, message='Username must be at least 3 characters long.')])),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Radiologist', 'Radiologist'), ('Technician', 'Technician'), ('Viewer', 'Viewer')], max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters long.')])),
                ('passwordChangedAt', models.DateTimeField(auto_now=True)),
                ('passwordResetToken', models.CharField(null=True)),
                ('lastPasswordChange', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('lastLogin', models.DateTimeField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
